apiVersion: v1
kind: PersistentVolume
metadata:
  name: ssh-honeypot-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /bulk/kubernetes/ssh-honeypot
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  claimRef:
    namespace: ssh-honeypot
    name: logdir
---    
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logdir
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ssh-honeypot
  name: ssh-honeypot
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:      
      app: ssh-honeypot
  template:
    metadata:
      labels:
        app: ssh-honeypot
    spec:
      containers:
      - name: ssh-honeypot
        image: ghcr.io/mmaschenk/docker-ssh-honeypot:main
        env:
        - name: ARGS
          value: -l /var/ssh-honeypot/logfile -r /var/ssh-honeypot/sshd-key.rsa -j /var/ssh-honeypot/logfile.json
        - name: TZ
          value: Europe/Amsterdam
        ports:
        - containerPort: 2022
          protocol: TCP
        resources:
          requests:
            memory: "5Mi"
            cpu: "250m"
          limits:
            memory: "25Mi"
            cpu: "500m"
        volumeMounts:
        - mountPath: /var/ssh-honeypot
          name: logdir
      restartPolicy: Always
      volumes:
      - name: logdir
        persistentVolumeClaim:
          claimName: logdir
---
apiVersion: v1
kind: Service
metadata:
  name: ssh-honeypot
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
  - port: 2022
    nodePort: 30022
  selector:
    app: ssh-honeypot
